---
title: "Hospital Length of Stay Models"
author: "You, Scientist"
format: html
---

```{r setup}

```

## Statement of Purpose

(Omitted for now -- try on your own for practice...)

## Introduction

(Omitted for now -- usually done at the end of a project...)

## Exploratory Data Analysis

(Partially Omitted for now -- try on your own for practice...)

Major steps...

+ Explore data set (No summary statistics here...try to avoid data leakage)

  + Print out *head*
  + Are there missing values?
  + Are any classes in your response variable rare?

+ **Do Today!** Split into training and test sets (be sure to set a seed)
+ Conduct EDA on *training* data only
  
  + Understand the distributions of your response variable and available predictors
  + Uncover associations between your response and the available predictors
  + Potentially probe for relationships between predictors -- this is particularly important if you want to interpret your model -- associated predictors cause problems for model interpretation when included in the same model

+ Summarize your findings and how they'll impact your model construction phase
  
## Model Construction

Goal(s) for October 13, 2023

  + Build and assess an "off the shelf" *nearest neighbors classifier*
  + Tune a *nearest neighbors classifier* to find the optimal number of voting neighbors -- tune other hyperparameters if you like as well
  + Add your model's predictions as columns to your training set (being able to add predictions to a data frame will be useful for CA3)
  
